functions/jeremydatud/js 103
jeremyhue1999/dotTheory---JavaScript pull request #3
Opened 2022-08-25 06:11 UTC by jeremyhue1999

# Related tickets
https://codeandtheory.atlassian.net/browse/JS-290

## Description
Adds the necessary codes for the task(functions). 

## Validation
Run HTML files
Change the url for the script attribute to see the different activities or challenges

2022-09-26 13:20 UTC, athanph commented on JS-103: JavaScript Functions/challenges/js/challenge2.js
> +  const year = new Date().getFullYear();
We can simplify this by immediately returning the value of year :
`return new Date().getFullYear();`

2022-09-26 13:24 UTC, athanph commented on JS-103: JavaScript Functions/challenges/js/challenge4.js
> +  if (num1 > num2) {
@jeremyhue1999 I know this is a challenge for if/else but in practice, we can simplify this as:
```
if (num1 > num2) return true;
return false;
```

2022-09-26 13:25 UTC, athanph commented on JS-103: JavaScript Functions/workspace/js/multiple-return.js
> +    false;
@jeremyhue1999 The `else` block lacks the `return` keyword.

2022-09-26 13:28 UTC, athanph requested changes
Left some comments to address.

2022-09-28 01:34 UTC, jeremyhue1999 commented
Good morning sir, 
I changed the things that you mentioned in the comments.

2022-09-30 09:43 UTC, merged